import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import Sidebar from './components/Sidebar';

import MainApp from "./MainApp";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Multi-vendor E-Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainApp>
          {children}
        </MainApp>
      </body>
    </html>
  );
}
