export type FormProduct = {
  name: string;
  product_type: string;
  price: number;
  discounted_price: number;
  discount_scheduled_from: string;
  discount_scheduled_to: string;
  // category: string;
  // weight: number;
  // length: number;
  // width: number;
  // height: number;
  // shipping_class: string;
  // tax_class: string;
  // tax_status: string;
  // is_wholesales_enabled: boolean;
  // wholesales_price: number; 
  // min_quantity_for_wholesales: number;
  // virtual: boolean; 
  is_downloadable: boolean; 
  description: string; 
  // discount_percentage: number;
  // min_quantity_for_discount: number;
  // allow_review: boolean;
  // min_order: number;
  // max_order: number;
  // product_status: string;
  // visibility: string;
  // product_notes: string;
  // add_to_cart: boolean;
  // hide_price: boolean;
  // stock: number;
  // is_stock_management_enabled: boolean;
  // low_stock_threshold: number;
  // stock_type: string; 
  // is_only_one: boolean;
  images: string[];
};
